import { randomBytes } from 'node:crypto'
import { mkdir, rename, writeFile, readFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { createServer } from 'node:https'
import httpProxy from 'http-proxy'
import { dirname, resolve } from 'node:path'
import { Client, ok, simpleFetchHandler } from '@atcute/client'
import type {} from '@atcute/atproto'
import { TestNetworkNoAppView } from '@atproto/dev-env'

const PDS_PORT = 2582
const PLC_PORT = 2583
const PDS_URL = `http://127.0.0.1:${PDS_PORT}`
const PLC_URL = `http://127.0.0.1:${PLC_PORT}`
const ORIGIN = 'http://127.0.0.1:3000'
const ENV_PATH = resolve('.env.test-network')
const certPath = resolve('.yak/tls/pds-cert.pem')
const keyPath = resolve('.yak/tls/pds-key.pem')
let tlsServer: ReturnType<typeof createServer> | undefined
let proxy: ReturnType<typeof httpProxy.createProxyServer> | undefined

const password = randomBytes(24).toString('base64url')
const sessionSecret = randomBytes(32).toString('base64url')
let network: TestNetworkNoAppView | undefined
let stopping = false

async function stop(exitCode = 0) {
  if (stopping) return
  stopping = true
  try {
    tlsServer?.closeAllConnections()
    tlsServer?.close()
    proxy?.close()
    await network?.close()
  } finally {
    process.exitCode = exitCode
  }
}

process.once('SIGINT', () => void stop())
process.once('SIGTERM', () => void stop())

try {
  await mkdir(dirname(certPath), { recursive: true, mode: 0o700 })
  if (!existsSync(certPath) || !existsSync(keyPath)) {
    execFileSync(
      'openssl',
      [
        'req',
        '-x509',
        '-newkey',
        'rsa:2048',
        '-nodes',
        '-keyout',
        keyPath,
        '-out',
        certPath,
        '-days',
        '30',
        '-subj',
        '/CN=pds.yak.test',
        '-addext',
        'subjectAltName=DNS:pds.yak.test'
      ],
      { stdio: 'ignore' }
    )
  }
  network = await TestNetworkNoAppView.create({
    plc: { port: PLC_PORT },
    pds: { port: PDS_PORT, hostname: 'pds.yak.test:2584' }
  })
  proxy = httpProxy.createProxyServer({ target: PDS_URL })
  proxy.on('error', (_error, _request, response) => {
    if ('writeHead' in response)
      response.writeHead(502).end('Test PDS unavailable')
  })
  tlsServer = createServer(
    { key: await readFile(keyPath), cert: await readFile(certPath) },
    (request, response) => proxy!.web(request, response)
  )
  await new Promise<void>(resolve => tlsServer!.listen(2584, resolve))

  const seed = network.getSeedClient()
  const owner = await seed.createAccount('owner', {
    handle: 'yak-owner.test',
    email: 'owner@example.test',
    password
  })
  await seed.createAccount('other', {
    handle: 'yak-other.test',
    email: 'other@example.test',
    password
  })

  const rpc = new Client({
    handler: async (pathname, init) => {
      const headers = new Headers(init.headers)
      headers.set('authorization', `Bearer ${owner.accessJwt}`)
      return simpleFetchHandler({ service: PDS_URL })(pathname, {
        ...init,
        headers
      })
    }
  })
  const now = new Date().toISOString()
  const publication = await ok(
    rpc.post('com.atproto.repo.createRecord', {
      input: {
        repo: owner.did,
        collection: 'site.standard.publication',
        record: {
          $type: 'site.standard.publication',
          name: 'Yak',
          url: ORIGIN
        }
      }
    })
  )
  await ok(
    rpc.post('com.atproto.repo.createRecord', {
      input: {
        repo: owner.did,
        collection: 'site.standard.document',
        record: {
          $type: 'site.standard.document',
          title: 'Hello from Yak',
          site: publication.uri,
          path: '/notes/hello',
          publishedAt: now,
          updatedAt: now,
          tags: ['React'],
          textContent: 'Hello from the isolated Yak development network.',
          content: {
            $type: 'at.markpub.markdown',
            flavor: 'commonmark',
            text: {
              $type: 'at.markpub.text',
              markdown: '# Hello from Yak\n\nThis document was seeded locally.'
            }
          }
        }
      }
    })
  )

  const env = [
    '# Generated by scripts/dev-network.mts; do not commit.',
    `YAK_OWNER_DID=${owner.did}`,
    `YAK_PDS_URL=${PDS_URL}`,
    `YAK_PLC_URL=${PLC_URL}`,
    `YAK_ORIGIN=${ORIGIN}`,
    'YAK_DEV_LOGIN=yak-owner.test',
    `YAK_DEV_PASSWORD=${password}`,
    `YAK_SESSION_SECRET=${sessionSecret}`,
    `NODE_EXTRA_CA_CERTS=${certPath}`,
    ''
  ].join('\n')
  const temporaryEnvPath = `${ENV_PATH}.${process.pid}.tmp`
  await writeFile(temporaryEnvPath, env, { mode: 0o600 })
  await rename(temporaryEnvPath, ENV_PATH)

  console.log(`Yak test network ready (PID ${process.pid})`)
  console.log(`PDS: ${PDS_URL}`)
  console.log(`PLC: ${PLC_URL}`)
  console.log(`Owner DID: ${owner.did}`)
  console.log(`Configuration written to ${ENV_PATH}`)
  console.log('Credentials and tokens are intentionally not printed.')
  console.log('Press Ctrl+C to stop and clean up the PLC and PDS.')

  await new Promise<void>(resolve => {
    process.once('SIGINT', resolve)
    process.once('SIGTERM', resolve)
  })
  await stop()
} catch (error) {
  console.error('Unable to start the isolated Yak test network.')
  await stop(1)
  throw error
}
